- name: "Download Harbor package"
  get_url:
    url: https://storage.googleapis.com/harbor-releases/release-1.8.0/harbor-offline-installer-v1.8.1.tgz
    dest: /tmp/harbor.tgz
    mode: '0744'

- name: "Extract Harbor tgz file"
  unarchive:
    src: /tmp/harbor.tgz
    dest: /tmp
    remote_src: yes
  args:
    creates: /tmp/harbor

- name: "Debug password HARBOR_ADMIN from env"
  debug:
    msg: "{{ lookup('env', 'HARBOR_ADMIN') }}"

- name: "Put Harbor template"
  template:
    src: harbor.yml.j2
    dest: /tmp/harbor/harbor.yml
    owner: root
    group: root
    mode: '0744'

- name: "Remove Harbor tgz file"
  file:
    path: /tmp/harbor.tgz
    state: absent

- name: "Install Harbor with Clair"
  shell: "/tmp/harbor/install.sh --with-clair"
  args:
    chdir: /tmp/
    creates: harbor-install.log
