- hosts: kubernetes
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: common }
    - { role: docker }
    - { role: kubernetes }

- hosts: masters
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: masters }
    - { role: wait }

- hosts: masters
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: contour }
    - { role: linkerd }
    - { role: helm }

- hosts: nodes
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: nodes }
    - { role: wait }

# nodes need to be ingressed first
- hosts: masters
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: cert-manager }
    - { role: wait }
    - { role: cert-manager-deploy }
    - { role: wait }
