- hosts: registry
  gather_facts: False
  remote_user: root
  become: yes
  # become_user: root
  # sudo: yes

  # pre_tasks:
    # - raw: apt update -yqq && apt install -yqq python-minimal

  roles:
    - { role: common }
    - { role: docker }
    - { role: letsencrypt }
    - { role: harbor }

  # post_tasks:
  #   - shell: apt update -yqq
