- hosts: registry
  gather_facts: True
  remote_user: root
  become: yes
  become_user: root
  roles:
    - { role: common }
    - { role: docker }
    - { role: letsencrypt }
    - { role: registry }
