all:
  vars:
    fqdn: ${FQDN}
    ansible_ssh_user: root
    cert_domain_name: registry.ondo.${FQDN}
    cert_admin_email: email@${FQDN}
  children:
    kubernetes:
      children:
        masters:
          vars:
            linkerd_fqdn: linkerd.ondo.${FQDN}
          hosts:
            0.0.0.0:
        nodes:
          hosts:
            0.0.0.0:
            0.0.0.0:
    registry:
      hosts:
        registry.ondo.${FQDN}
    front-proxy:
      hosts:
        0.0.0.0:
