- name: "Put Flannel template"
  template:
    src: kube-flannel.yml.j2
    dest: /tmp/flannel.yml
    owner: root
    group: root
    mode: '0777'

- name: "Apply Flannel"
  shell: kubectl -n kube-system apply -f /tmp/flannel.yml >> flannel_apply.log
  args:
    chdir: $HOME
    creates: flannel_apply.log
