- name: "Create Kubernetes cluster join token"
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: "Debug join_command_raw"
  debug:
    var: join_command_raw.stdout

- name: "Set join command as fact"
  set_fact: join_command="{{ join_command_raw.stdout }}"
