- name: "Install Envoy proxy required packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common

- name: "Add Envoy apt key"
  apt_key:
    url: https://getenvoy.io/gpg
    state: present

- name: "Add Envoy repo"
  apt_repository:
    repo: deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb bionic stable
    state: present
    filename: envoy

- name: "Install Envoy CLI"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - getenvoy-envoy

- name: "Create Envoy directory"
  file:
    path: /etc/envoy/
    state: directory
    owner: root
    group: root
    mode: "0777"

- name: "Put Envoy template"
  template:
    src:  envoy.yaml.j2
    dest: /etc/envoy/envoy.yaml
    owner: root
    group: root
    mode: "0777"

- name: "Create Envoy service file"
  template:
    src: envoy.system.j2
    dest: /etc/systemd/system/envoy.service
    owner: root
    group: root
    mode: "0777"

- name: "Reload systemd"
  # systemctl daemon-reload
  systemd: daemon_reload=yes

- name: "Start and enable Envoy service"
  # systemctl start envoy
  service: name={{ item }} state=started enabled=yes
  with_items:
    - envoy

- name: "Wait some time for envoy service to be up and running"
  shell: sleep 45
