- name: "Put Cert Manager template"
  template:
    src: cert-manager.yml.j2
    dest: /tmp/cert-manager.yml
    owner: root
    group: root
    mode: '0777'

- name: "Apply Cert Manager"
  shell: kubectl apply -f /tmp/cert-manager.yml >> cert_manager_apply.log
  args:
    chdir: $HOME
    creates: cert_manager_apply.log
